/**
 * Sarthi Vendor Application Version Configuration
 * Represents the version of the currently running frontend bundle.
 * Auto-generated by bump-version.js
 */

export const APP_VERSION = '1.2.26';
export const BUILD_TIME = '2026-09-07T12:22:00.614Z';
export const GIT_COMMIT = 'b286f17';

export const getActiveAppVersion = () => {
  return APP_VERSION;
};

export const setAcknowledgedVersion = (version) => {
  try {
    if (version) {
      sessionStorage.setItem('sarthi_vendor_acknowledged_version', String(version).trim());
    }
  } catch (e) {
    // Ignore storage issues
  }
};
