const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

function getGitCommitSha() {
    try {
        return execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim();
    } catch (e) {
        return (
            (process.env.VERCEL_GIT_COMMIT_SHA && process.env.VERCEL_GIT_COMMIT_SHA.slice(0, 7)) ||
            (process.env.GITHUB_SHA && process.env.GITHUB_SHA.slice(0, 7)) ||
            'dev'
        );
    }
}

function getCommitCount() {
    try {
        const count = execSync('git rev-list --count HEAD', { encoding: 'utf8' }).trim();
        const parsed = parseInt(count, 10);
        if (!isNaN(parsed) && parsed > 0) {
            return parsed;
        }
    } catch (e) {}
    return null;
}

/**
 * Reads or calculates the version dynamically based on git commit count,
 * guaranteeing every single deployment produces a strictly newer semantic version.
 */
function bumpVersion() {
    const versionFilePath = path.join(__dirname, '..', 'public', 'version.json');
    const packageJsonPath = path.join(__dirname, '..', 'package.json');
    const versionConfigPath = path.join(__dirname, '..', 'src', 'config', 'version.js');
    
    let buildTime = new Date().toISOString();
    let gitCommit = getGitCommitSha();
    let currentVersion = '1.2.21';
    if (fs.existsSync(packageJsonPath)) {
        try {
            const pkg = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
            if (pkg.version) currentVersion = pkg.version;
        } catch (e) {}
    } else if (fs.existsSync(versionFilePath)) {
        try {
            const data = JSON.parse(fs.readFileSync(versionFilePath, 'utf8'));
            if (data.version) currentVersion = data.version;
        } catch (e) {}
    }

    let newVersion;
    const commitCount = getCommitCount();
    // Offset 395: commit 415 -> 1.2.20, commit 417 -> 1.2.22, etc.
    if (commitCount && commitCount > 395) {
        const patch = commitCount - 395;
        newVersion = `1.2.${patch}`;
    } else {
        // Fallback for shallow clone in CI/CD environments (e.g. Vercel)
        const parts = currentVersion.split('.');
        if (parts.length >= 3) {
            const major = parts[0];
            const minor = parts[1];
            const patch = parseInt(parts[2], 10) || 0;
            newVersion = `${major}.${minor}.${patch + 1}`;
        } else {
            newVersion = currentVersion;
        }
    }

    const newVersionData = {
        version: newVersion,
        buildTime: buildTime,
        gitCommit: gitCommit
    };

    // 1. Write back to public/version.json
    fs.writeFileSync(versionFilePath, JSON.stringify(newVersionData, null, 2));

    // 2. Also keep package.json version in sync
    if (fs.existsSync(packageJsonPath)) {
        try {
            const pkg = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
            pkg.version = newVersion;
            fs.writeFileSync(packageJsonPath, JSON.stringify(pkg, null, 2));
        } catch (e) {}
    }

    // 3. Write directly into src/config/version.js
    const versionJsContent = `/**
 * Sarthi Vendor Application Version Configuration
 * Represents the version of the currently running frontend bundle.
 * Auto-generated by bump-version.js
 */

export const APP_VERSION = '${newVersion}';
export const BUILD_TIME = '${buildTime}';
export const GIT_COMMIT = '${gitCommit}';

export const getActiveAppVersion = () => {
  return APP_VERSION;
};

export const setAcknowledgedVersion = (version) => {
  try {
    if (version) {
      sessionStorage.setItem('sarthi_vendor_acknowledged_version', String(version).trim());
    }
  } catch (e) {
    // Ignore storage issues
  }
};
`;
    fs.writeFileSync(versionConfigPath, versionJsContent);

    // 4. Sync version.json to sub-apps public directories
    const subApps = ['railpad', 'sleeper-vendor'];
    subApps.forEach(sub => {
        const subPublic = path.join(__dirname, '..', sub, 'public');
        if (fs.existsSync(subPublic)) {
            fs.writeFileSync(path.join(subPublic, 'version.json'), JSON.stringify(newVersionData, null, 2));
        }
    });

    console.log(`🚀 Version auto-incremented to: ${newVersion} (Commit: ${gitCommit}, BuildTime: ${buildTime})`);

    return newVersionData;
}

if (require.main === module) {
    bumpVersion();
}

module.exports = { bumpVersion, getGitCommitSha };
